/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "You stumble across a strange looking amulet on your 25th birthday. It does not look like\n                                it has any worth on the market given that it's made from cheap-looking copper. However, you\n                                feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.": "你在 25 岁生日时偶然发现了一个看起来很奇怪的护身符。 它看起来不像\n 它在市场上没有任何价值，因为它是由看起来很便宜的铜制成的。 但是，您\n 有一种保留护身符的奇怪冲动，因此您将其放入口袋以妥善保管。",
    "Town Ruler": "镇长",
    "Town Ruler unlocked": "城镇统治者解锁",
    "Trained by a demon": "被恶魔训练",
    "Ultimate evil": "终极邪恶",
    "Ultra Speed": "超高速",
    "Under the bad influence": "在不良影响下",
    "Void Armor": "虚空护甲",
    "Void Universe": "虚空宇宙",
    "Void Universe unlocked": "虚空宇宙解锁",
    "VROOOOM": "VROOOOM",
    "Wait, it's made of bubblegum?": "等等，它是用泡泡糖做的？",
    "What Fire Nation?": "什么火之国？",
    "Where do I keep it?": "我在哪里保存它？",
    "Who turned the lights off?": "谁把灯关了？",
    "With the air, like I don't care, baby by the way": "随着空气，就像我不在乎，顺便说一句宝贝",
    "Wooden Hut": "木屋",
    "Worst person ever lived": "有史以来最糟糕的人",
    "You have done the thing!": "你已经做到了！",
    "I swear I don't have a problem": "我发誓我没有问题",
    "I'm a hot air balloon that could go to space": "我是一个可以去太空的热气球",
    "I'm the danger!": "我是危险！",
    "Import PK2": "导入骑士进度条2存档",
    "Improve your learning speed through practising intense concentration activities.": "通过练习集中注意力的活动来提高您的学习速度。",
    "Income /d": "收入/天",
    "It flows through my veins": "它流过我的血管",
    "It goes on its own": "它自己去",
    "It might seem crazy what I am 'bout to say": "我要说的话可能看起来很疯狂",
    "It's calling you!": "它在呼唤你！",
    "It's just a chair from IKEA": "这只是宜家的一把椅子",
    "It's shiny!": "它有光泽！",
    "Join the dark side": "加入黑暗面",
    "Learn to procrastinate less at work and receive more job experience per day.": "学会在工作中减少拖延，每天获得更多的工作经验。",
    "Legal youngster": "合法的年轻人",
    "Lifespan": "寿命",
    "lvl": "等级",
    "Lvl": "等级",
    "Meditation": "冥想",
    "Merging both worlds": "融合两个世界",
    "Miltary Jobs gain": "军队工作收益",
    "Miltary Jobs speed": "军队工作速度",
    "Multiverse Creator": "多元宇宙创造者",
    "Multiverse Creator unlocked": "多元宇宙创造者已解锁",
    "Multiverse Fragment": "多元宇宙碎片",
    "Muscle Memory": "肌肉记忆",
    "My back is starting to hurt": "我的背开始疼",
    "My block, my homies": "我的街区，我的兄弟们",
    "Nation Ruler": "国家统治者",
    "Nation Ruler unlocked": "国家统治者解锁",
    "Naughty boy": "淘气的男孩",
    "Net /d": "净收入/天",
    "Not homeless anymore": "不再无家可归",
    "Observatory": "天文台",
    "Own a Book": "拥有一本书",
    "Own a Butler": "拥有一个管家",
    "Own a Celestial Robe": "拥有一件天界长袍",
    "Own a Multiverse Fragment": "拥有一个多元宇宙碎片",
    "Own a Void Armor": "拥有一件虚空盔甲",
    "Own an Observatory": "拥有一个天文台",
    "Pay to win currency": "付钱赢钱",
    "Personal Squire": "个人侍从",
    "Plow the fields and grow the crops. It's not much but it's honest work.": "耕种田地，种植庄稼。这不是很多，但它是诚实的工作。",
    "Productivity": "工作效率",
    "Properties": "属性",
    "Proud owner of Taj Mahal": "泰姬陵的骄傲拥有者",
    "Ready for an adventure?": "准备好冒险了吗？",
    "Redemption arc": "救赎弧",
    "Repetition makes you stronger": "重复让你更强大",
    "Reset": "重置",
    "Ruby-licious": "红宝石",
    "Shabby logs and dirty hay glued together with horse manure. Much more sturdy than a tent, however, the stench isn't very pleasant.": "破旧的原木和肮脏的干草与马粪粘在一起。然而，比帐篷坚固得多，恶臭不是很令人愉快。",
    "Shop cost": "店铺成本",
    "Shop cost reduction 10%": "店铺成本降低 10%",
    "Skip": "跳过",
    "Sleep on the uncomfortable, filthy streets while almost freezing to death every night. It cannot get any worse than this.": "睡在不舒服、肮脏的街道上，每晚都几乎冻死。不能比这更糟了。",
    "Small Palace": "小宫殿",
    "Small Palace unlocked": "小宫殿解锁",
    "So heavy, I can't stand up": "太重了，站不起来",
    "So...what now?": "所以现在怎么办？",
    "Something pointy is growing on my forehead": "我的额头上长出了一个尖尖的东西",
    "Sorry I can't read": "抱歉我无法阅读",
    "Space bending": "空间弯曲",
    "Speed": "速度",
    "Squire": "侍从",
    "Stars in my eyes": "我眼中的星星",
    "Sticky substance": "粘性物质",
    "Strength": "力量",
    "Strength Skill speed": "力量技能速度",
    "Struggle day and night for a couple of copper coins. It feels like you are at the brink of death each day.": "为几枚铜币日夜奋斗。感觉就像你每天都在死亡的边缘。",
    "Study the tricks of the trade and persuasive skills to lower any type of expense.": "研究交易技巧和说服技巧以降低任何类型的费用。",
    "Sunshine she's here, you can take a break": "阳光她来了，你可以休息一下",
    "Super Speed": "超高速",
    "Swimming in it": "在里面游泳",
    "Tent": "帐篷",
    "Tent unlocked": "帐篷解锁",
    "The Devil himself": "魔鬼本人",
    "The Emperor's new clothes": "皇帝的新衣",
    "The four rivers of Hell": "地狱四河",
    "This operation is irreversible": "此操作不可逆",
    "Times change, or does it?": "时代变了，还是变了？",
    "Age": "年龄",
    "All Jobs & Skills Speed": "所有工作和技能速度",
    "Auto-learn ('S')": "自动学习 ('S')",
    "Auto-promote ('P')": "自动提升 ('P')",
    "Balance": "余额",
    "Battle Tactics": "战斗战术",
    "Beggar": "乞丐",
    "Current Job": "当前工作",
    "Current Skill": "当前技能",
    "Days": "\t\t天数",
    "Expenses /d": "费用/天",
    "Farmer": "农民",
    "FG Progress Knight": "FG骑士进度条",
    "Fisherman": "渔夫",
    "Happiness": "幸福",
    "...but where my furniture at?": "...但是我的家具在哪里？",
    "...but why?": "...但为什么？",
    "...I have people for that": "......我有这样的人",
    "...on the dark side": "...在黑暗的一面",
    "/d": "/d",
    "A maid man": "一个女仆",
    "Artefacts": "文物",
    "Auto-learn": "自动学习",
    "Auto-learn unlocked": "自动学习解锁",
    "Auto-pause": "自动暂停",
    "Auto-pause unlocked": "自动暂停解锁",
    "Auto-promote": "自动提升",
    "Auto-promote unlocked": "自动提升已解锁",
    "Ballin'": "巴林'",
    "Because I'm happy": "因为我开心",
    "Being evil pleases me": "作恶使我高兴",
    "Big bucks": "巨款",
    "Book": "书",
    "Butler": "管家",
    "Can't stop, won't stop": "停不下来，停不下来",
    "Celestial Robe": "天界长袍",
    "Clap along if you feel like a room without a roof": "如果您觉得自己像一个没有屋顶的房间，请鼓掌",
    "Clap along if you feel like happiness is the truth": "如果你觉得幸福是真的，就鼓掌",
    "Click": "点击",
    "Click once": "单击一次",
    "Coins": "硬币",
    "Count": "数数",
    "Current": "当前",
    "Deja vu?": "似曾相识？",
    "Destiny in your own hands": "命运掌握在自己手中",
    "Ebay rat": "易趣 老鼠",
    "Embrace evil": "拥抱邪恶",
    "Embrace Evil": "拥抱邪恶",
    "Essence": "精华",
    "Essence hoarder": "精华囤积者",
    "Essence symbiosis": "精华共生",
    "Eternal pain": "永恒的痛苦",
    "Everything must end": "一切都必须结束",
    "Evil": "邪恶",
    "Ew, it's slimy": "额，黏糊糊的",
    "Features": "功能",
    "Galactic fuel": "银河燃料",
    "Galactic Throne": "银河王座",
    "Galactic Throne unlocked": "银河王座解锁",
    "Galactic wallet": "银河钱包",
    "Game time": "游戏时间",
    "Gotta catch them all": "必须抓住他们",
    "Gotta go fast": "必须快点",
    "Grand Palace": "大宫殿",
    "Grand Palace unlocked": "大皇宫解锁",
    "Halfway there": "到了一半",
    "Hard Reset": "硬重置",
    "Hoarder": "囤积者",
    "House": "房子",
    "House unlocked": "房子解锁",
    "Hyper Speed": "超高速",
    "I did it for the sake of doing it": "我是为了做它而做的",
    "I have windows now!": "我现在有窗户！",
    "I hope there is no chocolate inside of it": "我希望里面没有巧克力",
    "Longest": "最长",
    "Rebirth": "重生",
    "Transcension": "超越",
    "A place to write down all your thoughts and discoveries, allowing you to learn a lot more quickly.": "一个写下你所有想法和发现的地方，让你学得更快。",
    "A thin sheet of tattered cloth held up by a couple of feeble, wooden sticks. Horrible living conditions but at least you have a roof over your head.": "几根软弱的木棍支撑着一块破布。 糟糕的生活条件，但至少你有一个屋顶。",
    "All Jobs speed": "所有工作速度",
    "All Skills speed": "所有技能速度",
    "Assists you in completing day to day activities, giving you more time to be productive at work.": "帮助您完成日常活动，让您有更多时间在工作中高效工作。",
    "Bargaining": "讨价还价",
    "Concentration": "专注",
    "Condition your body and strength through harsh training. Stronger individuals are paid more in the military.": "通过严格的训练来调节你的身体和力量。 更强壮的人在军队中的报酬更高。",
    "Create and revise battle strategies, improving experience gained in the military.": "创建和修改战斗策略，提高在军队中获得的经验。",
    "Dumbbells": "杠铃",
    "Heavy tools used in strenuous exercise to toughen up and accumulate strength even faster than before.": "用于剧烈运动的重型工具比以前更快地增强和积累力量。",
    "Homeless": "无家可归",
    "Miner": "矿工",
    "Reel in various fish and sell them for a handful of coins. A relaxing but still a poor paying job.": "卷入各种鱼并以少量硬币出售。 一份轻松但收入仍然很低的工作。",
    "Cottage": "茅屋",
    "Structured with a timber frame and a thatched roof. Provides decent living conditions for a fair price.": "结构为木框架和茅草屋顶。 以合理的价格提供体面的生活条件。",
    "On your 45th birthday, you feel the amulet shiver uncontrollably in your pocket. You take it\n                                out and the constant shivering suddenly stops. More to your bizarre surprise, you notice\n                                a strange etching on the centre of the amulet.": "在您 45 岁生日时，您会感到口袋里的护身符不受控制地颤抖。 你把它拿出来，不断的颤抖突然停止了。 更令您惊讶的是，您注意到护身符中心有一个奇怪的蚀刻。",
    "A fine blade used to slay enemies even quicker in combat and therefore gain more experience.": "用于在战斗中更快地杀死敌人并因此获得更多经验的精美刀片。",
    "Age has caught up to you": "年龄已经赶上了你",
    "Steel Longsword": "钢长剑",
    "Your age has met your lifespan, use the amulet to rebirth before you pass away": "你的年龄已经到了你的寿命极限，在你去世之前使用护身符重生",
    "Footman": "步兵",
    "Carry around your knight's shield and sword along the battlefield. Very meager pay but the work experience is quite valuable.": "在战场上随身携带骑士的盾牌和剑。 工资很低，但工作经验很有价值。",
    "1 + the max level of the job or skill / 10.": "1 + 工作或技能的最高等级 / 10。",
    "2 whole centuries": "2 整个世纪",
    "and reach its final form after": "并在之后达到最终形式",
    "and transform even further after living for\n                                    a": "并在生活后更进一步\n",
    "Blacksmith": "铁匠",
    "bonus": "奖励",
    "By touching the eyeball, you will be reborn and have to restart life again, losing all your levels and coins.\n                                    However, you will gain": "触摸眼球，你将重生，必须重新开始生活，失去所有等级和硬币。\n但是，你会获得",
    "Delve into dangerous caverns and mine valuable ores. The pay is quite meager compared to the risk involved.": "深入危险的洞穴并开采有价值的矿石。 与所涉及的风险相比，报酬相当微薄。",
    "for your jobs and skills equivalent to:": "你的工作和技能相当于：",
    "millennium": "千年",
    "Something tells you that the amulet might evolve after living for": "有人告诉你，护身符可能会在生存后进化",
    "ten millenia": "十万年",
    "This means you will learn everything again much more quickly than you did in your previous life.": "这意味着您将比前世更快地再次学习所有内容。",
    "On your 65th birthday, you once again encounter the strange, unexplained shivering from your\n                                    amulet. But this time, a living eyeball emerges from the centre. Although terribly frightened,\n                                    you realise you do not have many years to live left anyway so you consider touching the eye\n                                    to see what happens.": "在您的 65 岁生日那天，您再次遇到\n 护身符奇怪的、无法解释的颤抖。 但这一次，一个活生生的眼球从中心出现。 虽然非常害怕，\n你意识到你已经没有多少年可以活了，所以你考虑触摸眼睛\n看看会发生什么。",
    "Max": "最大",
    "Fill your mind with peace and tranquility to tap into greater happiness from within.": "让你的心灵充满平静与安宁，从内心获得更大的幸福。",
    "Mana Control": "法力控制",
    "Put down your life to battle with enemy soldiers. A courageous, respectable job but you are still worthless in the grand scheme of things.": "放下你的生命与敌方士兵战斗。 一份勇敢、受人尊敬的工作，但在宏伟的计划中你仍然一文不值。",
    "Strengthen your neurons through habit and repetition, improving strength gains throughout the body.": "通过习惯和重复来增强你的神经元，提高整个身体的力量增益。",
    "Student": "学生",
    "Veteran Footman": "资深步兵",
    "Merchant": "商人",
    "Smelt ores and carefully forge weapons for the military. A respectable and OK paying commoner job.": "为军队冶炼矿石并精心打造武器。 一份受人尊敬且报酬还可以的平民工作。",
    "Centenary": "百年纪念",
    "More experienced and useful than the average footm… battle with your might. The pay is not that bad.": "比普通人更有经验和有用……用你的力量战斗。 工资没那么差。",
    "Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n                                    A mouth emerges from its surface and begins to cackle, and proceeds to say: \"So you've made it this far... Are you ready to embrace evil?\"": "你的直觉是对的。 在您达到 200 岁的那一刻，您会听到护身符发出不祥的嗡嗡声。\n 一张嘴从它的表面露出并开始咯咯地笑，然后继续说：“所以你已经做到了这一步...... . 你准备好拥抱邪恶了吗？\"",
    "A thousand years have come and gone and yet, you still remain alive... somehow. You feel your amulet shivering again and to your surprise, you see small tendrils\n                                    full of eyeballs emergin from it. As you are about to drop the amulet, you hear frightening screech followed by whispers in your head...": "一千年过去了，然而，你仍然活着……不知何故。 你感到你的护身符再次颤抖，令你惊讶的是，你看到小藤蔓\n长满了眼球。 当你即将放下护身符时，你会听到可怕的尖叫声，然后是耳语在你的脑海中......",
    "Spend your days administrating The Arcane Association and investigate the concepts of true immortality. The chairman receives ludicrous amounts of pay daily.": "花你的时间管理奥术协会并研究真正不朽的概念。董事长每天收到可笑的薪水。",
    "Stores a collection of books, each containing vast amounts of information from basic life skills to complex magic spells.": "存放着一系列书籍，每本书都包含从基本生活技能到复杂魔法的大量信息。",
    "Strengthen your mana channels throughout your body, aiding you in becoming a more powerful magical user.": "加强你全身的法力通道，帮助你成为更强大的魔法使用者。",
    "Study Desk": "学习桌",
    "Study the theory of mana and practice basic spells. There is minor pay to cover living costs, however, this is a necessary stage in becoming a mage.": "学习法力理论并练习基本法术。支付生活费用的报酬很少，但是，这是成为法师的必要阶段。",
    "Tame the raging and growing evil within you, improving evil gain in-between rebirths.": "驯服你内心肆虐和增长的邪恶，提高重生之间的邪恶收益。",
    "Tapping into the powers of the Void while combining them with evil grants you an ulimited potential.": "在将虚空与邪恶结合的同时，利用虚空的力量赋予你无限的潜力。",
    "Temporal Dimension": "时间维度",
    "The most powerful and essential equipment of any Celestial. Acts as a source of infinite power.": "任何天体中最强大和最重要的装备。作为无限力量的源泉。",
    "The power to fulfill absolutely any and all wishes without any limitations.": "绝对满足任何和所有愿望的权力，没有任何限制。",
    "The Void": "虚空",
    "The Void Jobs speed": "空虚的工作速度",
    "There are few who may tread the paths between worlds, these powers grant you an ability to generate fields of void energy that devour all living things.": "很少有人可以踏上世界之间的道路，这些力量赋予你产生吞噬所有生物的虚空能量场的能力。",
    "Through the means of dark magic, multiply the raw matter of the coins you receive from your job.": "通过黑魔法的手段，倍增你从工作中获得的硬币的原材料。",
    "Time Loop": "时间循环",
    "Turn the tides of battle through casting intermediate spells and mentor other apprentices. The pay for this particular job is extremely high.": "通过施展中级法术和指导其他学徒扭转战局。这项特殊工作的薪水非常高。",
    "Under the supervision of a skilled mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.": "在熟练的法师的监督下，在战斗中对敌人施展基本法术。将提供丰厚的报酬以支付生活费用。",
    "Unknown how or when the Void realm came into existence, containing elements which don’t exist outside of its dimensional plane are now all to your disposal": "未知虚空领域是如何或何时出现的，包含不存在于其次元位面之外的元素现在都由你支配",
    "Used for observing terrestrial, marine and celestial events.": "用于观测陆地、海洋和天体事件。",
    "Utilise advanced spells to ravage and destroy entire legions of enemy soldiers. Only a small percentage of mages deserve to attain this role and are rewarded with an insanely high pay.": "利用先进的法术蹂躏和摧毁敌方士兵的整个军团。只有一小部分法师配得上这个角色，并获得高得离谱的报酬。",
    "Void Amplification": "虚空增幅",
    "Void Blade": "虚空之刃",
    "Void Dust": "虚空之尘",
    "Void Fiend": "虚空恶魔",
    "Void Influence": "虚空影响",
    "Void Lord": "虚空领主",
    "Void Manipulation": "虚空操纵",
    "Void Manipulation Skills Speed": "虚空操纵技能速度",
    "Void Necklace": "虚空项链",
    "Void Orb": "虚空宝珠",
    "Void Realm": "虚空境",
    "Void Reaver": "虚空掠夺者",
    "Void Shift": "虚空偏移",
    "Void Slave": "虚空奴隶",
    "Void Symbiosis": "虚空共生",
    "Void Wraith": "虚空怨灵",
    "When the orb touches non void entities, it instantly disintegrate them. Harnesting its power from Void realm.": "当球体接触到非虚空实体时，它会立即分解它们。从虚空领域汲取力量。",
    "Yin Yang": "阴阳",
    "You become an inquisitive yet putrid creature that siphons life from everything around you.": "你变成了一个好奇而腐烂的生物，从你周围的一切中吸取生命。",
    "You have to embrace the Void...": "你必须拥抱虚空……",
    "You have unlocked": "你已解锁",
    "You reign the whole nation, while your riches may be corrupted, everything you see belongs to you.": "你统治了整个国家，虽然你的财富可能被腐化，但你所看到的一切都属于你。",
    "You rule your very own community in your small town, owning multiple establishments.": "你在你的小镇上统治着你自己的社区，拥有多个机构。",
    "You surrender yourself to the Void, making it easier to take control of you.": "你将自己投降于虚空，更容易控制你。",
    "You wield an unlimited power, making you unstoppable. By ruling with an iron fist, everyone in the Arcane Association has to obey your commands.": "你拥有无限的力量，让你势不可挡。通过铁腕统治，奥术协会的每个人都必须服从你的命令。",
    ", all of your levels, coins and even max levels will be reset.\n                                    You will be reborn as a fresh slate. However, you will unlock a new line of skills and gain": "，您的所有等级、金币甚至最高等级都将被重置。\n您将重生为新的石板。但是，您将解锁新的技能线并获得",
    ", and which will heavily impact your future lives.": "，这将严重影响你未来的生活。",
    "A building formed from stone bricks and sturdy timber, which contains a few rooms. Although quite expensive, it is a comfortable abode.": "由石砖和坚固的木材组成的建筑物，其中包含几个房间。虽然很贵，但是住的很舒服。",
    "A dedicated area which provides many fine stationary and equipment designed for furthering your progress in research.": "一个专门的区域，提供许多精美的文具和设备，旨在促进您的研究进展。",
    "A Dimension just for you, that can be summoned at will. What happens there stays there.": "一个专为你而设的维度，可以随意召唤。那里发生的事情留在那里。",
    "A grand residence completely composed of gold and silver. Provides the utmost luxurious and comfortable living conditions possible for a ludicrous price.": "一座完全由金银组成的宏伟住宅。以可笑的价格提供最豪华和舒适的生活条件。",
    "A mere human body is too feeble and weak to withstand evil. Train with forbidden methods to slowly manifest into a demon, capable of absorbing knowledge rapidly.": "单纯的人体实在是太虚弱无力，无法抵挡邪恶。修炼禁法，慢慢化身为魔，快速吸收知识。",
    "A symbiotic relationship that helps you become one with the Void.": "一种共生关系，可帮助您与虚空合一。",
    "A technique designed to manipulate human thought and action against their desire.": "一种旨在操纵人类思想和行动违背其欲望的技术。",
    "A very rich and meticulously built structure rimmed with fine metals such as silver. Extremely high expenses to maintain for a lavish lifestyle.": "一个非常丰富且精心打造的结构，边缘镶有银等精美金属。维持奢侈生活方式的费用极高。",
    "abilities.": "能力。",
    "Absolute Wish": "绝对的愿望",
    "Abyss Anomaly": "深渊异常",
    "Adept Mage": "熟练法师",
    "Age speed": "年龄速度",
    "Age speed ('W')": "年龄速度（'W'）",
    "All Jobs & Skills speed": "所有工作和技能速度",
    "All Jobs gain": "所有工作获得",
    "All Seeing Eye": "全视之眼",
    "Almightness Jobs Speed": "全能工作速度",
    "Apprentice Mage": "学徒法师",
    "Arcane Jobs gain": "奥术工作获得",
    "Arcane Jobs speed": "奥术工作速度",
    "Archmage": "大法师",
    "As the highest rank of T.A.A, all funds go directly to you.": "作为 T.A.A 的最高级别，所有资金都直接归您所有。",
    "As the highest ranking official, you manage and oversee everything that happens, while your pay is astronomical, so are your expenses.": "作为最高级别的官员，您管理和监督发生的一切，而您的薪水是天文数字，您的开支也是如此。",
    "Astral Body": "星体",
    "Astral Realm": "星界",
    "Auto-pause (' ')": "自动暂停 (' ')",
    "Bend space and time through forbidden techniques, speeding up your learning processes.": "通过禁止的技术弯曲空间和时间，加快你的学习过程。",
    "Beneath personality and ego lays the source of our deep character, our personhood. Here are the psychic senses, our deep mind and emotions, symbols and inner reality.": "在个性和自我之下，是我们深刻性格的源泉，我们的人格。这是精神感官，我们深刻的思想和情感，符号和内在现实。",
    "Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that an archamge has enough destructive power to wipe an empire off the map.": "拥有无与伦比的天赋，随心所欲地用魔法完成令人难以置信的壮举。据说大魔王的破坏力足以将一个帝国从地图上抹去。",
    "Blood Meditation": "血液冥想",
    "Born from chaos when the universe was first created, believed to exist in harmony, balancing evil and good.": "宇宙初生时从混沌中诞生，相信和谐共处，平衡善恶。",
    "Brainwashing": "洗脑",
    "Ceaseless Abyss": "无尽深渊",
    "Chairman": "主席",
    "Chronomancer": "时空术士",
    "City Ruler": "城市统治者",
    "class category along with": "类类别以及",
    "Corrupted": "腐化",
    "Corrupted by Void, you are slowly turning into a slave with no free will, just to serve the Void for the rest of eternity... Can you resist it, or will it consume you forever?": "被虚空腐蚀，你正在慢慢变成一个没有自由意志的奴隶，只为永远为虚空服务……你能抗拒它，还是它会永远吞噬你？",
    "Creating your own pocket dimension where centuries go by in mere seconds.": "创建您自己的口袋维度，几个世纪就在几秒钟内过去。",
    "Damned soul... a shadow of your former self, lingering between realms and consumed by void... can you ever find peace?": "该死的灵魂……你以前的自己的影子，徘徊在各个领域之间，被虚空吞噬……你能找到平静吗？",
    "Dark Influence": "黑暗影响",
    "Dark Knowledge": "黑暗知识",
    "Dark Magic Jobs Speed": "黑魔法工作速度",
    "Demon Training": "恶魔训练",
    "Demons Wealth": "恶魔财富",
    "Each day you are succumbing to the Void more and more, can you hold to your humanity for a bit longer, or will you let it devour you?": "每天你都越来越屈服于虚空，你能坚持你的人性更久，还是让它吞噬你？",
    "Embedded with a rare sapphire, this charm activates more mana channels within your body, providing a much easier time learning magic.": "这款护身符嵌入了稀有蓝宝石，可激活体内更多的法力通道，让学习魔法更加轻松。",
    "Encompass yourself with formidable power bestowed upon you by evil, allowing you to pick up and absorb any job or skill with ease.": "用邪恶赋予你的强大力量包围自己，让你轻松掌握和吸收任何工作或技能。",
    "evil": "邪恶",
    "Evil & Essence gain": "邪恶与精华增益",
    "Evil Control": "邪恶控制",
    "Evil gain": "邪恶增益",
    "Forged from void dust and dark matter, can slash through dimensional barriers. It's a weapon of choice for every Void Reaver.": "由虚空尘埃和暗物质锻造而成，可以冲破次元屏障。它是每个虚空掠夺者的首选武器。",
    "Fundamental Skills Speed": "基本技能速度",
    "Galactic Jobs Speed": "银河工作速度",
    "Generates an innate armor as a part of you body, which is resistant to attacks, harm or pain.": "生成一种与生俱来的盔甲作为你身体的一部分，它可以抵抗攻击、伤害或疼痛。",
    "Grow and culture the evil within you through the sacrifise of other living beings, drastically increasing evil gain.": "通过牺牲其他众生来培养和培养你内心的邪恶，大大增加邪恶增益。",
    "Helps you shape and manipulate void matter, even transmute it and rebuild into anything of your choosing.": "帮助您塑造和操纵虚空物质，甚至将其转化并重建为您选择的任何东西。",
    "If you decide to embrace": "如果你决定拥抱",
    "Imperator": "统帅",
    "In a trance like state, you feel the Void controlling your thoughts, perception, memories, emotions and personality.": "在恍惚状态中，你会感觉到虚空控制着你的思想、感知、记忆、情绪和个性。",
    "Intimidation": "恐吓",
    "k": "ķ",
    "Keeps your household clean at all times and also prepares three delicious meals per day, leaving you in a happier, stress-free mood.": "让您的家庭时刻保持清洁，每天还准备三顿可口的饭菜，让您拥有更快乐、无压力的心情。",
    "Large House": "大房子",
    "Learn to emit a devilish aura which strikes extreme fear into other merchants, forcing them to give you heavy discounts.": "学会散发出令其他商人极度恐惧的恶魔气息，迫使他们给你大量折扣。",
    "Lengthen your lifespan drastically beyond comprehension by harnessing ethereal energy.": "通过利用空灵的能量，大大延长您的寿命。",
    "Lengthen your lifespan through the means of magic. However, is this truly the immortality you have tried seeking for...?": "通过魔法延长你的寿命。然而，这真的是你努力寻求的不朽吗……？",
    "Lets you see memories, remember images, and even see new pictures and ideas.": "让您看到回忆、记住图像，甚至看到新的图片和想法。",
    "Library": "图书馆",
    "Life Essence": "生命精华",
    "M": "M",
    "Magic Skills speed": "魔法技能速度",
    "Master Wizard": "巫师大师",
    "Mastery is achieved when \"telling time\" becomes \"telling time what to do\".": "当“告诉时间”变成“告诉时间该做什么”时，就达到了精通。",
    "Mind's Eye": "心灵的眼睛",
    "Mind's Seize": "心灵的占有",
    "Much larger than a regular house, which boasts even more rooms and multiple floors. The building is quite spacious but comes with a hefty price tag.": "比拥有更多房间和多层楼的普通房子大得多。该建筑非常宽敞，但价格却很高。",
    "Never ending torture, you swore to serve the Void for the rest of your existence.": "永无止境的折磨，你发誓终生为虚​​空服务。",
    "Parallel Universe": "平行宇宙",
    "Pocket Dimension": "口袋尺寸",
    "Predating our own universe, the Void has an ulimited amount of space for your belongings, if you are willing to submit to it.": "早于我们自己的宇宙，虚空有无限的空间存放你的物品，如果你愿意服从的话。",
    "Purest version of void created material, a teaspoon of it is as heavy as a small planet.": "最纯粹的虚空创造材料，一茶匙就跟一颗小行星一样重。",
    "Sapphire Charm": "蓝宝石吊饰",
    "Screaming into existence, you become a manifestation of the unknowable nothingness that lies beyond.": "尖叫着进入存在，你成为超越彼岸的不可知的虚无的化身。",
    "Sealed for a very long time, you utilized these forbidden texts for your own personal gain.": "封印了很长时间，你利用这些禁书为自己谋取私利。",
    "Self-contained plane of existence, co-existing with one's own, helping you restore fragments of your forgotten power.": "自给自足的存在位面，与自己的共存，帮助你恢复被遗忘的力量碎片。",
    "Specialize in harnessing temporal energies that alter the flow of time with supernatural divinations and otherwordly expertise.": "专注于利用时间能量，通过超自然的占卜和其他专业知识改变时间的流动。",
    "By proving your skills with a bow, you were appointed to lead a small group of archers to ambush your enemies from a distance.": "通过用弓证明你的技能，你被任命带领一小群弓箭手从远处伏击你的敌人。",
    "Feared by nations, obliterate entire armies in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.": "万国畏惧，眨眼间歼灭全军。几乎每个世纪，只有一位圣骑士配得上如此尊贵的称号。",
    "Holy Knight": "圣骑士",
    "Knight": "骑士",
    "Lieutenant General": "中将",
    "More experienced and useful than the average footman, take out the enemy forces in battle with your might. The pay is not that bad.": "比普通步兵更有经验和有用，在战斗中用你的力量消灭敌军。工资没那么差。",
    "Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while equipped magically imbued blade. Such a feared unit on the battlefield is paid extremely well.": "以非凡的熟练度一口气消灭敌方士兵的中队，同时装备魔法灌输的刀片。战场上这样一个令人恐惧的单位，薪水非常好。",
    "Slash and pierce through enemy soldiers with ease, while covered in steel from head to toe. A decently paying and very respectable job.": "轻而易举地砍杀并刺穿敌方士兵，同时从头到脚全身覆盖着钢铁。一份体面的薪水和非常受人尊敬的工作。",
    "Travel from town to town, bartering fine goods. The job pays decently well and is a lot less manually-intensive.": "从一个城镇到另一个城镇旅行，以物易物。这项工作的薪水不错，而且人工密集程度要低得多。",
    "Utilising your unmatched combat ability, slaugher enemies effortlessly. Most footmen in the military would never be able to acquire such a well paying job like this.": "利用你无与伦比的战斗能力，毫不费力地屠杀敌人。军队中的大多数步兵永远无法获得如此高薪的工作。",
    "Veteran Knight": "资深骑士",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    "All rights reserved.": "All rights reserved.",
    '© Freddec Games 2022': '© Freddec Games 2022',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Time Warping": "时间扭曲",
    "Touch the eye": "触摸眼球",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^ ([\d\.,]+)$/,
    /^ x([\d\.,]+)$/,
    /^ \>\= ([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Happy (.+)th!$/, '幸福达到 $1！'],
    [/^Have (.+) active miscs$/, '拥有 $1 活跃的杂项'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^Start with age of ([\d\.]+)$/, '从 $1 岁开始'],
    [/^Game speed \+([\d\.]+)\%$/, '游戏速度 \+$1\%'],
    [/^Happiness \+([\d\.]+)\%$/, '幸福 \+$1\%'],
    [/^Evail gain \+([\d\.]+)\%$/, '邪恶增益 \+$1\%'],
    [/^Essence gain \+([\d\.]+)\%$/, '精华增益 \+$1\%'],
    [/^Lifespan \+([\d\.]+)\%$/, '寿命 \+$1\%'],
    [/^Click ([\d\.]+) ([\d\.]+)$/, '邪恶 $1 $2'],
    [/^Evil ([\d\.]+)$/, '邪恶 $1'],
    [/^Transcension ([\d\.]+)$/, '超越 $1'],
    [/^Embrace Evil ([\d\.]+)$/, '拥抱邪恶 $1'],
    [/^Essence ([\d\.]+)$/, '精华 $1'],
    [/^Happiness ([\d\.]+)$/, '幸福 $1'],
    [/^Hoarder ([\d\.]+)$/, '囤积者 $1'],
    [/^Transcension x([\d\.]+)$/, '超越 x$1'],
    [/^Embrace Evil x([\d\.]+)$/, '拥抱邪恶 x$1'],
    [/^([\d\.]+) Gold$/, '$1 黄金'],
    [/^([\d\.]+) Platinum$/, '$1 铂'],
    [/^Happiness \>\= (.+)$/, '幸福 \>\= $1'],
    [/^Click \>\= (.+)$/, '点击 \>\= $1'],
    [/^Essence \>\= (.+)$/, '精华 \>\= $1'],
    [/^Evil \>\= (.+)$/, '邪恶 \>\= $1'],
    [/^Age \>\= (.+)$/, '年龄 \>\= $1'],
    [/^Balance \>\= (.+) Ruby$/, '余额 \>\= $1 红宝石'],
    [/^Balance \>\= (.+) Silver$/, '余额 \>\= $1 银币'],
    [/^Balance \>\= (.+) Ruby$/, '余额 \>\= $1 红宝石'],
    [/^Balance \>\= (.+) Gold$/, '余额 \>\= $1 黄金'],
    [/^Balance \>\= (.+) Platinum$/, '余额 \>\= $1 铂金'],
    [/^(.+) Ruby$/, '$1 红宝石'],
    [/^([\d\.]+) Silver$/, '$1 银币'],
    [/^([\d\.]+) miles per hour!$/, '$1 英里每小时！'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);